name: Backend CI/CD
permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths: [ 'amaima/backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'amaima/backend/**' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ""
      API_SECRET_KEY: "test_secret_key_for_ci"
      NVIDIA_NIM_API_KEY: "test_nim_key_for_ci"
      # FHE_ENABLED=false skips TenSEAL import in engine.py so tests
      # don't require the native C++ extension to be installed.
      # FHE unit tests that specifically need TenSEAL are skipped via
      # @pytest.mark.skipif(not TENSEAL_AVAILABLE, reason="TenSEAL not installed")
      FHE_ENABLED: "false"
      PYTHONPATH: "."
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: amaima/backend/requirements.txt

      - name: Install dependencies
        run: |
          cd amaima/backend
          python -m pip install --upgrade pip
          # Install all deps except tenseal — not needed for CI test run
          # and its native C++ extension adds 2-5 min to CI with no benefit.
          # FHE_ENABLED=false means engine.py won't attempt to import it.
          grep -v "tenseal" requirements.txt | pip install --no-cache-dir -r /dev/stdin

      - name: Run tests
        run: |
          cd amaima/backend
          pytest tests/ -v --tb=short
